######### REQUETES MONSTRES SANS TOKEN ###################

### Afficher tous les monstres
GET http://localhost:3000/monstre/

### afficher 1 monstre par son nom
GET http://localhost:3000/monstre/goblin

### Ajout de monstre (sans token pour le moment)
POST http://localhost:3000/monstre/ajouter/orc

### Suppression de monstre par nom (sans token pour le moment)
DELETE http://localhost:3000/monstre/supprimer/orc


### Modification du monstre par nom (changement de nom et changement de la stat attaque)
PATCH HTTP://localhost:3000/monstre/goblin
Content-Type: application/json

{
    "nom":"Goblin ++",
    "attaque": 50
}

### Suppression du nouveau monstre cree lors de la modification
DELETE http://localhost:3000/monstre/supprimer/goblin ++

###########################################################