### Variables globales
@baseUrl = http://localhost:3000

######### REQUETES AUTH #########

### Créer un compte Admin
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "admin@maxremi.com",
    "pseudo": "AllSeeingEye",
    "mdp": "MdP123456!lol",
    "codeAdmin": "AdminTest123"
}


### Créer un compte comme utilisateur
POST http://localhost:3000/auth/register
Content-Type: application/json
{
    "email": "math_le_barbare@waaagh.com",
    "pseudo": "DakkaBoii",
    "mdp": "WaaAgh247!"
}

### Login dans un compte Admin avec infos OK
# @name loginAdmin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@maxremi.com",
    "mdp": "MdP123456!lol"
}

### authTokenAdmin garde en mémoire le token admin pour l'utiliser dans d'autres routes
@authTokenAdmin = {{loginAdmin.response.body.token}}


### Login dans un compte comme utilisateur avec infos OK
# @name loginReq
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "math_le_barbare@waaagh.com",
    "mdp": "WaaAgh247!"
}

### authToken garde en mémoire le token du login pour l'utiliser dans d'autres routes
@authToken = {{loginReq.response.body.token}}

### Login dans un compte comme utilisateur avec un mauvais MDP
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "math_le_barbare@waaagh.com",
    "mdp": "wAAaGH247!"
}

### Login dans un compte comme utilisateur avec un mauvais pseudo
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "math_le_barbare@waagh.com",
    "mdp": "WaaAgh247!"
}

### Obtenir mes informations d'utilisateur
GET http://localhost:3000/auth/me
Authorization: Bearer {{authToken}}


######### REQUETES MONSTRES ###################

### Afficher tous les monstres (PUBLIC)
GET http://localhost:3000/monstre/

### afficher 1 monstre par son nom (PUBLIC)
GET http://localhost:3000/monstre/goblin

### Ajout de monstre (MDJ)
POST http://localhost:3000/monstre/ajouter/orc
Authorization: Bearer {{authTokenAdmin}}

### Ajout de monstre (MDJ)
POST http://localhost:3000/monstre/ajouter/goblin
Authorization: Bearer {{authTokenAdmin}}

### Suppression de monstre par nom (MDJ)
DELETE http://localhost:3000/monstre/supprimer/orc
Authorization: Bearer {{authTokenAdmin}}

### Modification du monstre par nom (changement de nom et changement de la stat attaque) (MDJ)
PATCH HTTP://localhost:3000/monstre/goblin
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "nom":"Goblin ++",
    "attaque": 50
}

### Suppression du nouveau monstre cree lors de la modification (MDJ)
DELETE http://localhost:3000/monstre/supprimer/goblin%20++
Authorization: Bearer {{authTokenAdmin}}

######### REQUETES OBJETS SANS TOKEN ###################

### Creer 1 objet (MDJ)
POST http://localhost:3000/objet/creer
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "nom": "Baton",
    "rarete": "RARE"
}

### Afficher tous les objets (PUBLIC)
GET http://localhost:3000/objet/

### afficher 1 objet par son nom (PUBLIC)
GET http://localhost:3000/objet/baton


### Suppression de objet par nom (MDJ)
DELETE http://localhost:3000/objet/supprimer/baton
Authorization: Bearer {{authTokenAdmin}}


### Modification du objet par nom (changement de nom et changement de la rarete) (MDJ)
PATCH HTTP://localhost:3000/objet/baton
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "nom":"Baton Legendaire",
    "rarete": "LEGENDAIRE"
}

### Suppression de l'objet modifié par son nouveau nom (MDJ)
DELETE http://localhost:3000/objet/supprimer/baton%20Legendaire
Authorization: Bearer {{authTokenAdmin}}


######### REQUETES QUETES ###################

### Creer 1 quete (MDJ)
POST http://localhost:3000/quete/creer
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "nom": "Aller chercher le baton",
    "difficulte": "FACILE",
    "recompense" : 100
}

### Creer 2e quete (sans token pour le moment)
POST http://localhost:3000/quete/creer
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "nom": "Vaincre Grok",
    "difficulte": "DIFFICILE",
    "recompense" : 150
}

### Afficher tous les quetes (PUBLIC)
GET http://localhost:3000/quete

### Afficher tous les quetes par difficulte (PUBLIC)
GET http://localhost:3000/quete?difficulte=difficile


### afficher 1 quete par son nom (PUBLIC)
GET http://localhost:3000/quete/Aller%20chercher%20le%20baton


### Suppression de quete par nom (MDJ)
DELETE http://localhost:3000/quete/supprimer/Aller%20chercher%20le%20baton
Authorization: Bearer {{authTokenAdmin}}


### Modification de quete par nom (changement de difficultee et changement de la recompense) (MDJ)
PATCH HTTP://localhost:3000/quete/Aller%20chercher%20le%20baton
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "nom": "Aller chercher le baton ++",
    "difficulte": "DIFFICILE",
    "recompense" : 1000
}

######### REQUETES UTILISATEURS (MDJ) ###################

# ajoutez un id d'utilisateur valide dans la variable @uuidUser pour les tests - IMPORTANT: Pas de ""
@uuidUser = 358697cf-563a-4a0b-8516-b35980b4d76e

### Créer un utilisateur (MAITRE_DU_JEU)
POST {{baseUrl}}/utilisateur/creer
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "email": "test-utilisateur@gmail.com",
    "pseudo": "test-utilisateur",
    "mdp": "mdp-test-utilisateur"
}

### Récupérer l'information d'un utilisateur

GET {{baseUrl}}/utilisateur/recuperer/{{uuidUser}}
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

### Mettre à jour un utilisateur
PATCH {{baseUrl}}/utilisateur/modifier/{{uuidUser}}
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "email": "test-utilisateur2@gmail.com",
    "pseudo": "test-utilisateur2",
    "mdp": "mdp-test-utilisateur2"
}

### Supprimer un utilisateur
DELETE {{baseUrl}}/utilisateur/supprimer/{{uuidUser}}
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

######### REQUETES PERSONNAGES ###################

### Créer un personnage (JOUEUR) -- S'assurer que la variable uuidUser contient bien un id utilisateur valide
POST {{baseUrl}}/personnage/creer
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "nom": "Gandalf",
    "classe": "MAGE",
    "idUtilisateur": "{{uuidUser}}"
}

###

# uuidPerso doit contenir un id de personnage valide pour les tests suivants
@uuidPerso = d9af2f02-222a-4eb1-97e6-66347e791f76
@uuidQuete = 6f9110e0-f4ce-49fc-bfb0-7df2c29c53b8

### Récupérer l'information d'un personnage 
GET {{baseUrl}}/personnage/recuperer/{{uuidPerso}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Mettre à jour un personnage
PATCH {{baseUrl}}/personnage/modifier/{{uuidPerso}}
Content-Type: application/json
Authorization: Bearer {{authTokenAdmin}}

{
    "nom": "Donkey Kong",
    "classe": "GUERRIER",
    "piecesDOr": 1000
}

### Supprimer un personnage
DELETE {{baseUrl}}/personnage/supprimer/{{uuidPerso}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

######### PERSOQUETE - JOURNAL DE QUETES #########

### Ajouter une quete a la table intermediaire persoquete
POST http://localhost:3000/persoquete/ajouter
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "idPerso": "{{uuidPerso}}",
    "idQuete": "{{uuidQuete}}"
}

### Voir le journal de quete d'un personnage

GET http://localhost:3000/persoquete/{{uuidPerso}}
Authorization: Bearer {{authToken}}